//
//  Strings.swift
//  ZAND
//
//  Created by Василий on 18.04.2023.
//

import Foundation

enum AssetString {
    static let where_wanna_go = "Куда хотите пойти?"
    static let filter = "Фильтры"
    static let hair = "Волосы"
    static let nail = "Ногти"
    static let spa = "SPA"
    static let face_care = "Уход"
    static let makeUp = "Визаж"
    static let brows = "Брови"
    static let viewOnMap = "Посмотреть на карте"
    static let grades = "Оценок"
    static let address = "Адрес"
    static let weekDays = "Будние дни"
    static let weekendDays = "Выходные"
    static let description = "Описание"
    static let showCase = "Витрина"
    static let entrance = "Вход"
    static let forgotPassword = "Забыли пароль?"
    static let registation = "Регистрация"
    static let accountExist = "Уже есть аккаунт?"
    static let confirmEmail = "Подтвердите Email"
    static let showFirst = "Показать сначала"
    static let services = "Услуги"
    static let reset = "Сбросить"
    static let userName = "#username"
    static let favourites = "Избранное"
    static let phoneNumber = "Номер телефона"
    static let pushesAboutOrder = "Пуши о заказе"
    static let writeAboutBook = "Напишем, когда подтвердим запись"
    static let feature = "Предстоящие"
    static let was = "Прошедшие"
    static let mens = "Мужчинам"
    static let exitMessage = "Вы точнно хотите выйти?"
    static let no = "Нет"
    static let yes = "Да"
    static let from = "от"
    static let rub = "руб."
    static let skip = "Пропустить"
    static let search = "Поиск"
    static let cancel = "Отмена"
    static let empty = "Пока что пусто"
    static let ok = "Понятно"
    static let smsCode = "Код из смс"
    static let enterYourName = "Вы не написали своё имя :)"
    static let phoneNumberLessThanEleven = "Общее количество символов телефона должно быть 11"
    static let codeIsInvalid = "Код не верен"
    static let sendCode = "Отправить код"
    static let enterYourCode = "Введите код"
    static let gotError = "Произошла ошибка"
    static let getCode = "Получить код"
    static let enterPhone = "Введите номер телефона"
    static let youIsNotRegister = "Вы не вошли в аккаунт"
    static let pleaseRegister = "Для просмотра профиля войдите в аккаунт"
    static let invalidEmailInput = "Неверный ввод почты"
    static let shouldAcceptPolicy = "Необходимо ознакомиться с политикой конфиденциальности"
    static let howStart = "С чего начать?"
    static let selectService = "Выбрать услуги"
    static let selectStaff = "Выбрать специалиста"
    static let service = "Услуги"
    static let staff = "Специалисты"
    static let findInServices = "Найти в услугах"
    static let selectDateAndTime = "Выберите дату и время"
    static let checkAppointment = "Проверьте запись"
    static let approveAppointment = "Подтвердите запись"
    static let chooseTime = "Выберите время"
    static let finalText = "Поздравляем! Запись оформлена!"
    static let errorText = "Произошла ошибка :("
    
    // MARK: - Bottom button values
    static let apply = "Применить"
    static let enter = "Войти"
    static let register = "Зарегистрироваться"
    static let book = "Записаться"
    static let contin = "Далее"
    static let callUs = "Свяжитесь с нами"
    static let myData = "Мои данные"
    static let pushSms = "Уведомления и смс"
    static let phoneInputError = "Ошибка ввода номера телефона"
    static let tryAgain = "Попробуйте еще раз"
    static let fillAllFields = "Заполните все поля"

    // MARK: - Padding textfield
    static let email = "Email"
    static let password = "Пароль"
    static let name = "Имя"
    static let surname = "Фамилия"
    static let age = "Возраст"
    static let user_name = "@username"
    static let confirmPassword = "Подтвердите пароль"
    static let confirmationCode = "Код подтверждения"
    
    // MARK: - Filter options
    static let highGrade = "Высокий рейтинг"
    static let chip = "Недорогие"
    static let expensive = "Дорогие"
    
    // MARK: - ProfileMenu
    static let books = "Записи"
    static let details = "Мои данные"
    static let logOut = "Выйти"
    
    // MARK: - Tabbar
    static let main = "Главная"
    static let map = "Карта"
    static let profile = "Профиль"
}
