//
//  Strings.swift
//  ZAND
//
//  Created by Василий on 18.04.2023.
//

import Foundation

enum AssetString: String {
    case where_wanna_go = "Куда хотите пойти?"
    case filter = "Фильтры"
    case hair = "Волосы"
    case nail = "Ногти"
    case massage = "Массаж"
    case spa = "SPA"
    case cosmetology = "Косметология"
    case eyes = "Глаза"
    case epilation = "Эпиляция"
    case viewOnMap = "Посмотреть на карте"
    case grades = "Оценок"
    case address = "Адрес"
    case weekDays = "Будние дни"
    case weekendDays = "Выходные"
    case description = "Описание"
    case showCase = "Витрина"
    case entrance = "Вход"
    case forgotPassword = "Забыли пароль?"
    case registation = "Регистрация"
    case accountExist = "Уже есть аккаунт?"
    case confirmEmail = "Подтвердите Email"
    case showFirst = "Показать сначала"
    case reset = "Сбросить"
    case userName = "#username"
    case favourites = "Избранное"
    case phoneNumber = "Номер телефона"
    case pushesAboutOrder = "Пуши о заказе"
    case writeAboutBook = "Напишем, когда подтвердим запись"
    case feature = "Предстоящие"
    case was = "Прошедшие"
    case mens = "Мужчинам"
    case exitMessage = "Вы точнно хотите выйти?"
    case no = "Нет"
    case yes = "Да"
    case from = "от"
    case rub = "руб."
    case skip = "Пропустить"
    case search = "Поиск"
    case cancel = "Отмена"
    case empty = "Пока что пусто"
    case ok = "Понятно"
    case smsCode = "Код из смс"
    case enterYourName = "Вы не написали своё имя :)"
    case phoneNumberLessThanEleven = "Общее количество символов телефона должно быть 11"
    case codeIsInvalid = "Код не верен"
    case sendCode = "Отправить код"
    case enterYourCode = "Введите код"
    case gotError = "Произошла ошибка"
    case getCode = "Получить код"
    case enterPhone = "Введите номер телефона"
    case youIsNotRegister = "Вы не вошли в аккаунт"
    case pleaseRegister = "Для просмотра профиля войдите в аккаунт"
    case invalidEmailInput = "Неверный ввод почты"
    case shouldAcceptPolicy = "Необходимо ознакомиться с политикой конфиденциальности"
    case howStart = "С чего начать?"
    case selectService = "Выбрать услуги"
    case selectStaff = "Выбрать специалиста"
    case service = "Услуги"
    case staff = "Специалисты"
    case findInServices = "Найти в услугах"
    case selectDateAndTime = "Выберите дату и время"
    case checkAppointment = "Проверьте запись"
    case approveAppointment = "Подтвердите запись"
    case chooseTime = "Выберите время"
    case finalText = "Поздравляем! Запись оформлена!"
    case errorText = "Произошла ошибка :("
    case phoneInput = "Номер телефона должен начинаться с +7 (9..."
    case deleteProfile = "Удалить профиль"
    case areYouSure = "Вы уверены?"
    case managerWillPhone = "Для удаления профиля наш менеджер свяжется в Вами"
    case checkYourData = "Проверьте свои данные"
    case fix = "Исправить"
    case good = "Как надо!"
    case phone = "Телефон"
    case noAppointments = "Записей нет"
    case areUsureCancelAppointment = "Вы точно хотите отменить запись?"
    case appointmentWillDeleteForever = "Ваша запись удалится безвозвратно"
    case cancelAppointment = "Отменить запись"
    case appointmentDeleted = "Запись отменена"
    case appointmentProvided = "Услуга оказана"
    case appointmentNotProvided = "Услуга не оказана"
    case time = "Время"
    case noSalons = "В данной категории салоны отсутствуют"
    case save = "Сохранить"
    case geoIsOff = "Мы заметили, что вы отключили передачу данных о местоположении. Желаете снова активировать данную функцию, чтобы мы могли показывать ближайшие салоны?"
    case willOn = "Включить?"
    case all = "Все"
    case badConnection1 = "⚠️ Не забудьте выключить VPN, он тормозит работу приложения!"
    case badConnection2 = "ℹ️ При плохом интернет-соединении информация может обновляться дольше"
    case resetPassword = "Восстановление пароля"
    case refreshPassword = "Обновить пароль"
    case birthday = "Дата рождения"
    case done = "Готово"
    case passwIsNotEqual = "Пароли не совпадают"
    case passwordCountIsSmall = "Пароль должен содержать минимум 8 символов"
    case invalidEmailOrPassword = "Почта или пароль не верны"

    // MARK: - Bottom button values
    case apply = "Применить"
    case enter = "Войти"
    case register = "Зарегистрироваться"
    case book = "Записаться"
    case contin = "Далее"
    case callUs = "Свяжитесь с нами"
    case pushSms = "Уведомления и смс"
    case phoneInputError = "Ошибка ввода номера телефона"
    case tryAgain = "Попробуйте еще раз"
    case fillAllRequiredFields = "Заполните все обязательные поля"

    // MARK: - Padding textfield
    case email = "Email"
    case password = "Пароль"
    case name = "Имя"
    case surname = "Фамилия"
    case fathersName = "Отчество"
    case age = "Возраст"
    case user_name = "@username"
    case createPassword = "Придумайте пароль"
    case confirmPassword = "Подтвердите пароль"
    case repeatPassword = "Повторите пароль"
    case confirmationCode = "Код подтверждения"
    case near = "Ближайшие"
    
    // MARK: - Filter options
    case highGrade = "Высокий рейтинг"
    case chip = "Недорогие"
    case expensive = "Дорогие"
    
    // MARK: - ProfileMenu
    case books = "Записи"
    case details = "Мои данные"
    case logOut = "Выйти"
    
    // MARK: - Tabbar
    case main = "Главная"
    case map = "Карта"
    case profile = "Профиль"
}
